
# Local 환경
spring:
  config:
    activate:
      on-profile: "db-local"
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_LOCAL_USERNAME}
    password: ${SPRING_DATASOURCE_LOCAL_PASSWORD}
    url: ${SPRING_DATASOURCE_LOCAL_URL}
  data:
    redis:
      host: ${REDIS_LOCAL_HOST_NAME}
      port: ${REDIS_LOCAL_PORT}
      username: ${REDIS_LOCAL_USERNAME}
      password: ${REDIS_LOCAL_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

---
# Production 환경
spring:
  config:
    activate:
      on-profile: "db-prod"
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_PROD_USERNAME}
    password: ${SPRING_DATASOURCE_PROD_PASSWORD}
    url: ${SPRING_DATASOURCE_PROD_URL}
  data:
    redis:
      host: ${REDIS_PROD_HOST_NAME}
      port: ${REDIS_PROD_PORT}
      username: ${REDIS_PROD_USERNAME}
      password: ${REDIS_PROD_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_PROD_SERVICE_URL}