# Default 설정
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 10
    open-in-view: false

---
# Local 환경
spring:
  config:
    activate:
      on-profile: "db-local"
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_LOCAL_USERNAME}
    password: ${SPRING_DATASOURCE_LOCAL_PASSWORD}
    url: ${SPRING_DATASOURCE_LOCAL_URL}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      username: ${SPRING_DATA_REDIS_USERNAME}
      password: ${SPRING_DATA_REDIS_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}


---
# Production 환경
spring:
  config:
    activate:
      on-profile: "db-prod"
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_PROD_USERNAME}
    password: ${SPRING_DATASOURCE_PROD_PASSWORD}
    url: ${SPRING_DATASOURCE_PROD_URL}
  data:
    redis:
      host: ${REDIS_PROD_HOST_NAME}
      port: ${REDIS_PROD_PORT}
      username: ${REDIS_PROD_USERNAME}
      password: ${REDIS_PROD_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_PROD_SERVICE_URL}

---
