# default
server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active:
      - prod
    group:
      local:
        - db-local
      prod:
        - db-prod
    include:
      - db
      - infra

