# default
server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active:
      - prod
    group:
      local:
        - db-local
      prod:
        - db-prod
    include:
      - db



api:
  key:
    ${REST_API_KEY}


management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0
