### 회원 가입
POST http://localhost:19093/api/auth/signup
Content-Type: application/json
Accept: application/json

{
  "username": "user123",
  "password": "Qwer1234@",
  "email": "user123@email.com",
  "tel": "010-1234-5678",
  "slackId": "slack-id",
  "role": "HUB_MANAGER",
  "adminToken": null
}

### 로그인
POST http://localhost:19093/api/auth/login
Content-Type: application/json

{
  "email": "master123@email.com",
  "password": "Qwer1234@"
}

### 내 정보 조회
GET http://localhost:19093/api/user/2
Content-Type: application/json

### 유저 전체 조회 (MASTER)
GET http://localhost:19093/api/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6Ik1BU1RFUiIsImlzcyI6InVzZXItc2VydmljZSIsImlhdCI6MTczMzkxOTkzMiwiZXhwIjoxNzMzOTIwMjkyfQ.5_47UQCW9rhLFu_AsTMdSs4NN9Stz7gn829AmJMvxjVzTwNDtYwSzMmHr5VTa5Y_TFkMkNWrkh3xqzvQjHHzsg
Content-Type: application/json
X-User-Id: 1
X-User-Role: MASTER

### 유저 권한 수정 (MASTER)
PATCH http://localhost:19093/api/user/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6Ik1BU1RFUiIsImlzcyI6InVzZXItc2VydmljZSIsImlhdCI6MTczMzkxOTkzMiwiZXhwIjoxNzMzOTIwMjkyfQ.5_47UQCW9rhLFu_AsTMdSs4NN9Stz7gn829AmJMvxjVzTwNDtYwSzMmHr5VTa5Y_TFkMkNWrkh3xqzvQjHHzsg
Content-Type: application/json
X-User-Id: 1
X-User-Role: MASTER

{
  "role": "COMPANY_MANAGER"
}

### 유저 탈퇴
DELETE http://localhost:19093/api/user/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6Ik1BU1RFUiIsImlzcyI6InVzZXItc2VydmljZSIsImlhdCI6MTczMzkxOTkzMiwiZXhwIjoxNzMzOTIwMjkyfQ.5_47UQCW9rhLFu_AsTMdSs4NN9Stz7gn829AmJMvxjVzTwNDtYwSzMmHr5VTa5Y_TFkMkNWrkh3xqzvQjHHzsg
Content-Type: application/json
X-User-Id: 1
X-User-Role: MASTER

### 허브 매니저 생성
POST http://localhost:19093/api/hub-manager
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6Ik1BU1RFUiIsImlzcyI6InVzZXItc2VydmljZSIsImlhdCI6MTczNDAxOTAzOSwiZXhwIjoxNzM0MDE5Mzk5fQ.0S2Zk1Z9qwcOFrIZnnZ_V5nL1FhYu-5P7vCHSUhlnRNeFb2_qCzVq_qcWmMuIzzC34Mz7PxOaF-ggMp_2Nzqng
Content-Type: application/json
X-User-Id: 1
X-User-Role: MASTER
