### 회원 가입
POST http://localhost:19093/api/auth/signup
Content-Type: application/json
Accept: application/json

{
  "username": "user123",
  "password": "Qwer1234@",
  "email": "user123@email.com",
  "tel": "010-1234-5678",
  "slackId": "slack-id",
  "role": "HUB_MANAGER",
  "adminToken": null
}

### 로그인
POST http://localhost:19093/api/auth/login
Content-Type: application/json

{
  "email": "master123@email.com",
  "password": "Qwer1234@"
}

### 내 정보 조회
GET http://localhost:19093/api/user/2
Content-Type: application/json

### 유저 전체 조회 (MASTER)
GET http://localhost:19093/api/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6Ik1BU1RFUiIsImlzcyI6InVzZXItc2VydmljZSIsImlhdCI6MTczMzkxOTkzMiwiZXhwIjoxNzMzOTIwMjkyfQ.5_47UQCW9rhLFu_AsTMdSs4NN9Stz7gn829AmJMvxjVzTwNDtYwSzMmHr5VTa5Y_TFkMkNWrkh3xqzvQjHHzsg
Content-Type: application/json
X-User-Id: 1
X-User-Role: MASTER

### 유저 권한 수정 (MASTER)
PATCH http://localhost:19093/api/user/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6Ik1BU1RFUiIsImlzcyI6InVzZXItc2VydmljZSIsImlhdCI6MTczMzkxOTkzMiwiZXhwIjoxNzMzOTIwMjkyfQ.5_47UQCW9rhLFu_AsTMdSs4NN9Stz7gn829AmJMvxjVzTwNDtYwSzMmHr5VTa5Y_TFkMkNWrkh3xqzvQjHHzsg
Content-Type: application/json
X-User-Id: 1
X-User-Role: MASTER

{
  "role": "COMPANY_MANAGER"
}

### 유저 탈퇴
DELETE http://localhost:19093/api/user/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6Ik1BU1RFUiIsImlzcyI6InVzZXItc2VydmljZSIsImlhdCI6MTczMzkxOTkzMiwiZXhwIjoxNzMzOTIwMjkyfQ.5_47UQCW9rhLFu_AsTMdSs4NN9Stz7gn829AmJMvxjVzTwNDtYwSzMmHr5VTa5Y_TFkMkNWrkh3xqzvQjHHzsg
Content-Type: application/json
X-User-Id: 1
X-User-Role: MASTER

### 허브 매니저 생성
POST http://localhost:19093/api/hub-managers
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6Ik1BU1RFUiIsImlzcyI6InVzZXItc2VydmljZSIsImlhdCI6MTczNDA2MTcxNiwiZXhwIjoxNzM0MDYyMDc2fQ.IBZeNohwW1XD8WkeSiTntzmdy5fGYsSz8biR7ZHnTAbzyx99o_Fh6g5Jxj9mmRG99BkDEMx5DT0aQ0Uor5u9Tg
Content-Type: application/json
X-User-Id: 1
X-User-Role: MASTER

{
  "userId": 2,
  "hubId": "5864303b-849c-499a-82ec-f4151551bb7f"
}
